@api = http://127.0.0.1:3000/api/venta/descuentos

POST {{api}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjBmYTNkOGFjMWI0Y2UyZWYzNTNkYyIsInVzZXJuYW1lIjoiR3V0aGVyIER1YXJ0ZSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMDQ4MTY4MiwiZXhwIjoxNzMwNTY4MDgyfQ.r6-6qmD8nY0a9fNxwGj76J2fjgbpXdqxKAd_ob1W_WQ
Content-Type: application/json

{
  "nombre": "Descuento de Verano",
  "tipoDescuento": "porcentaje",
  "valorDescuento": 15,
  "fechaInicio": "2024-06-01T00:00:00.000Z",
  "fechaFin": "2024-08-31T23:59:59.000Z",
  "minimoCompra": 100,
  "minimoCantidad": 2,
  "activo": "true",
  "moneda_id": "671342d4664051db7c1f8792",
  "codigoDescunto": "VERANO2024",
  "tipoDescuentoEntidad": "Product",
  "productId": "6720fc058ac1b4ce2ef353f6"
}

###

GET {{api}}/67133f450dcdd2f9ee534c5c/branch
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjBmN2I3OGFjMWI0Y2UyZWYzNTNkNCIsInVzZXJuYW1lIjoicm9vdCIsInJvbGUiOiJyb290IiwiaWF0IjoxNzMwNTgwMTEzLCJleHAiOjE3MzA2NjY1MTN9.RhbS1wMmOoTHNkPwrB38OE0ePldPahrgWEBHK1U1_o8
