
@api = http://127.0.0.1:3000/api/branches

### ingresar usuario
POST {{api}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MGI2YzExYmY1Y2IyZmFlZjE2YjAzZiIsInVzZXJuYW1lIjoiQ2FybG9zIGd1dGhlciIsInJvbGUiOiJDYWplcm8iLCJpYXQiOjE3Mjk4MjAwNTMsImV4cCI6MTcyOTgyMzY1M30.61GF4rjkgQ6AWnJx6LOi2uw2r7SB8Zo9Jel74rgL1vE
Content-Type: application/json

{
    "nombre":"Tienda juigalpa",
    "direccion":"Frente al zona",
    "ciudad":"Boaco",
    "pais":"Brasil",
    "telefono":"123456789"
}

### get sucursales
GET {{api}}/67133f450dcdd2f9ee534c5c/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjBmN2I3OGFjMWI0Y2UyZWYzNTNkNCIsInVzZXJuYW1lIjoicm9vdCIsInJvbGUiOiJyb290IiwiaWF0IjoxNzMwMjIyMTA4LCJleHAiOjE3MzAyMjU3MDh9.3ex7qBW8ZXRKLEHIqnT65njJJV0iYsre7evpcnpeaRA

### get productos faltantes en la sucursal
GET {{api}}/67133f450dcdd2f9ee534c5c/products-shortages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjBmN2I3OGFjMWI0Y2UyZWYzNTNkNCIsInVzZXJuYW1lIjoicm9vdCIsInJvbGUiOiJyb290IiwiaWF0IjoxNzMwMjIyMTA4LCJleHAiOjE3MzAyMjU3MDh9.3ex7qBW8ZXRKLEHIqnT65njJJV0iYsre7evpcnpeaRA