@api = http://127.0.0.1:3000/api/users

@api2 = http://127.0.0.1:3000/api/auth

### ingresar usuario
POST {{api2}}/register
Content-Type: application/json

{
    "username":"Junior Hurtado",
    "password":"Mapamapa84",
    "role":"Cajero"
}

### login
POST {{api2}}/login
Content-Type: application/json

{
    "username":"Junior Hurtado",
    "password":"Mapamapa84"
}

##obtner profile
####
GET {{api}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzA0ZGE4MTkwMGRmNzdlNTYxOTczNmMiLCJ1c2VybmFtZSI6Ikp1bmlvciBIdXJ0YWRvIiwicm9sZSI6IkNhamVybyIsImlhdCI6MTcyODc4OTI4MSwiZXhwIjoxNzI4NzkyODgxfQ.Parma7LRmYiJApPDdljh3LXaC390pK4DY2yuZOepDAw